services:
  lms.api:
    image: ${DOCKER_REGISTRY-}lmsapi
    container_name: lms.api
    build:
      context: .
      dockerfile: LMS.API/Dockerfile
    ports:
    - 5000:8080
    - 5001:8081 
    depends_on : 
      lms.database: 
        condition: service_healthy
    restart: always
    networks : 
      - "default"

  lms.database:
    image: postgres:18-alpine
    container_name: lms.database
    environment: 
      - POSTGRES_DB:${DB_DATABASE}
      - POSTGRES_USER:${DB_USER}
      - POSTGRES_PASSWORD:${DB_PASSWORD} 
    volumes:
      - ./.containers/database:/var/lib/postgressql
    ports:
      - 5432:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U app -d appdb"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    networks : 
      - "default"

networks:
  default: 
    driver: bridge
    
  
      
